#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*														             Verkefni 3																									*|
|*                          Notum fjarstyringu til ad stjorna robotnum                                *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task idk(){
	while(1 == 1)
  {
    motor[leftMotor]  = (vexRT[Ch3] + vexRT[Ch4])/2;
    motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4])/2;
    motor[armMotor]  = vexRT[Ch2]/2;

    if(vexRT[Btn6U] == 1)
		{
			motor[clawMotor] = 127;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[clawMotor] = -127;
		}
		else
		{
			motor[clawMotor] = 0;
		}
  }
}


task start(){
	while(1==1){
		if(vexRT[Btn7D] == 1)
		{
			StartTask(idk);
			//StartTask(main);
		}
		if(vexRT[Btn8D] == 1)
		{
			StopTask(idk);
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			motor[armMotor] = 0;
			//StartTask(main);
		}
	}
}


task main ()
{
	StartTask(start);
	while(1==1){
		}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
